[package]
name = "firefly-vio-init"
version = "0.1.0"
keywords = ['vio', 'visual-inertial', 'initialization', 'robotics']
categories = ['robotics', 'science', 'algorithms']
edition = "2024"
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
firefly-vio-core = { workspace = true }
firefly-vio-types = { workspace = true }
log = { workspace = true }
nalgebra = { workspace = true }

[lints]
workspace = true
