[package]
name = "void"
version = "0.1.0"
keywords = ['divo', 'odometry', 'app', 'robotics']
categories = ['robotics', 'science', 'algorithms', 'mathematics']
edition = "2024"
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[[bin]]
name = "void"
path = "src/main.rs"

[dependencies]
fastrace = { workspace = true }
firefly-error = { workspace = true }
firefly-observability = { workspace = true }
firefly-pubsub = { workspace = true }
firefly-void = { workspace = true }
firefly-void-types = { workspace = true }
iceoryx2 = { workspace = true }
log = { workspace = true }
nalgebra = { workspace = true }

[lints]
workspace = true
