[package]
name = "vio"
version = "0.1.0"
keywords = ['vio', 'visual-inertial', 'msckf', 'robotics']
categories = ['robotics', 'science', 'algorithms']
edition = "2024"
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[[bin]]
name = "vio"
path = "src/main.rs"

[dependencies]
fastrace = { workspace = true }
firefly-error = { workspace = true }
firefly-observability = { workspace = true }
firefly-pubsub = { workspace = true }
firefly-vio = { workspace = true }
firefly-vio-core = { workspace = true }
firefly-vio-types = { workspace = true }
iceoryx2 = { workspace = true }
log = { workspace = true }
nalgebra = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
