[package]
name = "firefly-vio-types"
version = "0.1.0"
keywords = ['vio', 'visual-inertial', 'odometry', 'robotics']
categories = ['robotics', 'science', 'algorithms', 'mathematics']
edition = "2024"
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
nalgebra = { workspace = true }

[lints]
workspace = true
