[package]
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords = ['localization', 'slam', 'robotics']
categories = ['robotics', 'science', 'algorithms']
name = "localization"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "localization"
path = "src/main.rs"

[dependencies]
firefly-base.workspace = true
fastrace = { workspace = true }
firefly-error = { workspace = true }
firefly-localization = { workspace = true }
firefly-observability = { workspace = true }
firefly-pubsub = { workspace = true }
iceoryx2 = { workspace = true }
log = { workspace = true }
nalgebra = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
