[package]
name = "firefly-voxel-svio"
version = "0.1.0"
keywords = ['vio', 'voxel', 'msckf', 'robotics']
categories = ['robotics', 'science', 'algorithms']
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
fastrace = { workspace = true }
firefly-error = { workspace = true }
log = { workspace = true }
nalgebra = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
