"""firefly-mujoco：无人机 MuJoCo 物理环境库。

提供 [`DroneEnv`](firefly_mujoco.env.DroneEnv)（被控对象：物理步进 +
IMU/双目灰度/深度提取 + 施加旋翼推力）与跨语言消息契约
[`messages`](firefly_mujoco.messages)。控制律不在本库（唯一实现在 `firefly-flight`）。
"""

from .env import DroneEnv
from .messages import (
    AIRFRAME_TOPIC,
    COMMAND_KIND_ARM,
    COMMAND_KIND_DISARM,
    COMMAND_KIND_HOLD,
    COMMAND_KIND_LAND,
    COMMAND_KIND_TAKEOFF,
    COMMAND_KIND_TRACK,
    COMMAND_TOPIC,
    CONTROL_TOPIC,
    LOG_LEVEL_DEBUG,
    LOG_LEVEL_ERROR,
    LOG_LEVEL_INFO,
    LOG_LEVEL_TRACE,
    LOG_LEVEL_WARN,
    LOG_TEXT_MAX,
    LOG_TAG_MAX,
    LOG_TOPIC,
    PLANT_STATE_TOPIC,
    AirframeMessage,
    CommandMessage,
    ControlMessage,
    DepthImageMessage,
    GrayImageMessage,
    IMAGE_HEIGHT,
    IMAGE_SIZE,
    IMAGE_WIDTH,
    ImuMessage,
    LogMessage,
    OdomMessage,
    PlantStateMessage,
    ReferenceMessage,
    TraceContext,
)
from .scene import PAD_CLEARANCE, PADS, build_scene, drone_pad, load_scene_name

__all__ = [
    "DroneEnv",
    "build_scene",
    "load_scene_name",
    "drone_pad",
    "PADS",
    "PAD_CLEARANCE",
    "IMAGE_WIDTH",
    "IMAGE_HEIGHT",
    "IMAGE_SIZE",
    "TraceContext",
    "ImuMessage",
    "GrayImageMessage",
    "DepthImageMessage",
    "ReferenceMessage",
    "OdomMessage",
    "PlantStateMessage",
    "AirframeMessage",
    "ControlMessage",
    "CommandMessage",
    "LogMessage",
    "LOG_TOPIC",
    "PLANT_STATE_TOPIC",
    "AIRFRAME_TOPIC",
    "CONTROL_TOPIC",
    "COMMAND_TOPIC",
    "COMMAND_KIND_ARM",
    "COMMAND_KIND_DISARM",
    "COMMAND_KIND_TAKEOFF",
    "COMMAND_KIND_HOLD",
    "COMMAND_KIND_TRACK",
    "COMMAND_KIND_LAND",
    "LOG_LEVEL_ERROR",
    "LOG_LEVEL_WARN",
    "LOG_LEVEL_INFO",
    "LOG_LEVEL_DEBUG",
    "LOG_LEVEL_TRACE",
    "LOG_TAG_MAX",
    "LOG_TEXT_MAX",
]
