[package]
name = "firefly-render"
version = "0.1.0"
keywords = ['visualization', 'simulation', 'rendering']
categories = ['graphics', 'simulation', 'game-engines']
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
bevy = { workspace = true }

[lints]
workspace = true
