[package]
name = "firefly-flight"
version = "0.1.0"
keywords = ['control', 'simulation', 'robotics']
categories = ['simulation', 'aerospace']
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
glam = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
